# Generated by Django 2.0.5 on 2019-01-10 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 8, 50, 36, 449411)),
        ),
        migrations.AddField(
            model_name='sentences',
            name='description',
            field=models.CharField(default='some description', max_length=400),
        ),
        migrations.AddField(
            model_name='sentences',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
