# Generated by Django 2.0.5 on 2019-01-10 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190110_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentences',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 8, 58, 36, 717274)),
        ),
    ]
